# Generated by Django 4.1.7 on 2023-03-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Foundation',
            new_name='foundation',
        ),
    ]
